name: test

on: pull_request

jobs:
  test-multiple:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: migration handles multiple safe migrations
      uses: ./
      with:
        pattern: "test/multiple-safe/*.sql"
        version: "latest"
        upload-to-github: false
